### ISSUE TITLE
Manual is incorrect for "Download Checkpoints"

### ISSUE THREAD

**Issue by jfietz** [meta-llama/llama-agentic-system#34]
The llama program that has slightly different arguments than the documentaiton when installed witjh `pip install -e .` 

I.e., when trying to download the 8B model:
`llama download meta-llama/Meta-Llama-3.1-8B-Instruct` fails with 
```
➤ llama download meta-llama/Meta-Llama-3.1-8B-Instruct --hf-token REDACTED
usage: llama download [-h] --source {meta,huggingface} --model-id
                      {llama3_1_8b,llama3_1_70b,llama3_1_405b_bf16_mp8,llama3_1_405b_fp8_mp8,llama3_1_405b_bf16_mp16,llama3_1_8b_instruct,llama3_1_70b_instruct,llama3_1_405b_instruct_bf16_mp8,llama3_1_405b_instruct_fp8_mp8,llama3_1_405b_instruct_bf16_mp16}
                      [--hf-token HF_TOKEN] [--meta-url META_URL] [--ignore-patterns IGNORE_PATTERNS]
llama download: error: the following arguments are required: --source, --model-id
```
It's possible to download the instruction model by varying the paramters to `llama download --source huggingface  --hf-token REDACTED --model-id llama3_1_8b_instruct`.

However, the two guard models are not listed in the model-ids and I haven't quite found the way to trigger the download for them

**Comment by Chrecci** [comment]
Have you figured out another way to install yet, or what the correct model_ids might be

**Comment by ArtyomMinsk** [comment]
@jfietz try to reinstall requirements.txt

**Comment by jfietz** [comment]
> @jfietz try to reinstall requirements.txt

Same issue after a `pip install -r requirements.txt` (output suggested no changes and all requirements already being satisfied).

**Comment by dltn** [comment]
Hi @jfietz, what documentation are you referring to? Could you confirm you're able to download the guard models now via the listed `model-id`?

**Comment by jfietz** [comment]
I meant the README, but I see it was updated to match the new behavior as well in https://github.com/meta-llama/llama-agentic-system/commit/afa063097996eb815a98ec359defe94490f254eb#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L128-R131
