### ISSUE TITLE
Application startup failed:  Redirects are currently not supported in Windows or MacOs.

### ISSUE THREAD

**Issue by amruizva** [meta-llama/llama-agentic-system#7]
Yaml config:
------------------------
inference_config:
  impl_config:
    impl_type: inline
    checkpoint_config:
      checkpoint:
        checkpoint_type: pytorch
        checkpoint_dir: /
        tokenizer_path: /tokenizer.model
        model_parallel_size: 1
        quantization_format: bf16
    quantization: null
    torch_seed: null
    max_seq_len: 16384
    max_batch_size: 1

**Comment by dltn** [comment]
See #17
